### ISSUE TITLE
Invite everyone concerned

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#1]

**Comment by dvzrv** [comment]
This should be extended by writing to lac-team.
It will also be extended by crowdsourcing the camp, I'm sure.

**Comment by dvzrv** [comment]
I also notified #lac2015@freenode about the new channel.

**Comment by ri0t** [comment]
the irc webchat link is: http://webchat.freenode.net/?randomnick=1&channels=lac2016&uio=d4

**Comment by abrolag** [comment]
When will we see information generally publicised? It's getting very late :(

**Comment by dvzrv** [comment]
Announcement is out.
