### ISSUE TITLE
Determine Conference Date

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#10]
A date is necessary to ask for location reservations.

**Comment by dvzrv** [comment]
we could go for:
2016.03.31. - 2016.04.03
2016.04.07 - 2016.04.10

Those dates are still outside of semesters (at least for Germans). Easter is the week before the first date.
As a reference for public holidays, something like this can be used: http://feiertage.net/uebersicht.php

Are there any more dates we definitely have to avoid?

**Comment by ri0t** [comment]
i think the second week of april was the better choice. more chances of good weather (and outdoor area usage) too

**Comment by dvzrv** [comment]
Damn, no April's Fools joke n'all ;)

**Comment by ri0t** [comment]
i can ask for the other date too

**Comment by dvzrv** [comment]
How's that coming along?

**Comment by ri0t** [comment]
Since there is a lot of events on the weekend before the first date (easterholidays), we chose the second date:
2016-04-07 - 2016-04-10
