### ISSUE TITLE
Find institutions to cheaply rent audio equipment from

### ISSUE THREAD

**Issue by dvzrv** [linux-audio-berlin/LAC16#11]
For multi-channel works/ installations we could most likely rent cheaply from https://www.ak.tu-berlin.de/menue/elektronisches_studio/
Meyer UPL-1 ftw!

**Comment by dvzrv** [comment]
We should also ask speaker companies, if they're willing to either sponsor equipment for the installation space/ hack & roll, etc. or even sponsoring:
http://www.adam-audio.com/

**Comment by ri0t** [comment]
We should ping these guys: http://www.eve-audio.com

**Comment by dvzrv** [comment]
Definitely maybe both :)

**Comment by RhizomaticNomad** [comment]
For hack & roll we could probably get stuff from NewYorck59 (occupied space in Bethanien), depending what we need. There we have to give a donation but no fixed money.

**Comment by magnetophon** [comment]
I've also asked fusion-festival.de for options. They regularly support other organizations, for example last CCCamp.

**Comment by dvzrv** [comment]
We have a stereo setup in mainhall. We should think about maybe extending this to 4 or 8 channels, if possible.
Electronic Studio of TU is still going to cost minor rental/ insurance fees.
In any case: The Meyer UPL-1 I would only want to setup in the mainhall if there's no smoking allowed during them being around.
They're too expensive to spoil.

**Comment by magnetophon** [comment]
Is this issue still open?

The fusion people just asked me wether we still need their equipment.

**Comment by dvzrv** [comment]
@magnetophon not sure we'll actually still need this. Would only make sense in the seminar room, as we have usable setups in mainhall and soundlab. Do you know if we can get a small sized PA for the seminar room? If so, come by tomorrow evening at c-base at 19:30 (orga meeting)
P.S.: A short notify about that they actually offered anything would have been good when they offered it ;-)

**Comment by magnetophon** [comment]
@dvzrv: We probably can get one.
Should I request it from them?

**Comment by magnetophon** [comment]
We will probably have to get it ourselves, from Lärz, about an hour driving from Berlin.
Maybe that doesn't make sense if its just for one small PA...

**Comment by dvzrv** [comment]
@magnetophon: na, nevermind. Will get a small 8 channel active speaker setup from TU and the rest from the CCC.
