### ISSUE TITLE
Association and fonds sponsoring

### ISSUE THREAD

**Issue by dvzrv** [linux-audio-berlin/LAC16#17]
Hauptstadtkulturfonds (Capital Cultural Fonds) - http://www.hauptstadtkulturfonds.berlin.de/index.php?id=156

**Comment by ri0t** [comment]
Here's a list of the LAC15 sponsors that could be interesting:
- http://www.grame.fr/
- http://www.hku.nl/home-en.htm
- http://hoertech.de/web_en/start/

**Comment by ri0t** [comment]
Berlin (regional) co financing fonds:
- http://www.berlin.de/sen/kultur/foerderung/foerderprogramme/kofinanzierungsfonds/
  Very interesting, the Musicboard:
  http://www.musicboard-berlin.de/

**Comment by ri0t** [comment]
The ClubCommission could help: http://www.clubcommission.de/themen/clubconsult

**Comment by dvzrv** [comment]
DEGEM (http://www.degem.de/) wants to lent their name (according to Joachim Heintz).

**Comment by dvzrv** [comment]
The Linux Foundation (http://www.linuxfoundation.org/) must be asked.

**Comment by dvzrv** [comment]
We split the sponsoring chunk into three:
http://linuxaudio.berlin:9001/p/sponsoring-associations
http://linuxaudio.berlin:9001/p/sponsoring-corporations
http://linuxaudio.berlin:9001/p/sponsoring-press

All further collecting of data and updates should be done in the pad.

**Comment by dvzrv** [comment]
Sponsoring packages have been moved to: http://linuxaudio.berlin:9001/p/sponsoring-packages

**Comment by ri0t** [comment]
The pads have moved.

**Comment by dvzrv** [comment]
indeed, now:
https://pad.sleepmap.de/p/lac2016-sponsoring-associations
https://pad.sleepmap.de/p/lac2016-sponsoring-corporations
https://pad.sleepmap.de/p/lac2016-sponsoring-press
https://pad.sleepmap.de/p/lac2016-sponsoring-letter
https://pad.sleepmap.de/p/lac2016-sponsoring-packages

**Comment by dvzrv** [comment]
I'm currently also part-time working for http://hybrid-plattform.org
There might be a chance of getting some promotion out of this.
WIP

**Comment by ri0t** [comment]
Meh.
