### ISSUE TITLE
Generate labels and milestones

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#2]

**Comment by dvzrv** [comment]
Call for papers/ installations/ talks/ workshops
Sponsoring
Book hotel contingents
Print proceedings
Print flyers and posters

**Comment by ri0t** [comment]
Hmmmmm. We need the first flyers and stuff for the camp. so i'll add the camp meetup as small milestone.

**Comment by ri0t** [comment]
We now have a batbunch of new labels. I hope they are useful ,)

**Comment by ri0t** [comment]
I also created a bunch of hopefully useful milestones. not all mentioned above, though!
We still need to come up with rough dates for those!

**Comment by ri0t** [comment]
I fixed this!!11!
