### ISSUE TITLE
github issue notifications IRC integration

### ISSUE THREAD

**Issue by bgola** [linux-audio-berlin/LAC16#20]
https://cogo.wordpress.com/2012/11/07/irc-notifications-on-github/

@flavioamiero

**Comment by flavioamieiro** [comment]
I've tried to configure the github webhook, have to try it out, though.

**Comment by flavioamieiro** [comment]
Ok, I had missed a step here. This should work now.

**Comment by flavioamieiro** [comment]
Let's see if it works with "messages without join" enabled.

**Comment by ri0t** [comment]
hello? Is this thing on?

**Comment by ri0t** [comment]
Weeee, i'm on IRC \o/
