### ISSUE TITLE
Setup a Frab instance for content planning

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#24]
https://github.com/frab/frab

**Comment by dvzrv** [comment]
We might want to set this up for http://lac.linuxaudio.org.
On lac-team@lists.linuxaudio.org we can ask, who is running the current servers and if we can install frab there, so it can be reused.

**Comment by ri0t** [comment]
Ideally we have this and #25 on separate virtual machines (docker containers would be nice) so we can instantiate and back them up easily as well as deploy them anywhere. I would deploy them on a soon-to-be-gotten machine in the soundlab.

**Comment by ri0t** [comment]
Oh, that is possibly already solved:
https://hub.docker.com/r/gglnx/frab/
https://hub.docker.com/r/mpfeil/docker-frab/

**Comment by dvzrv** [comment]
Got a wiki to do this: http://frab.linuxaudio.org
