### ISSUE TITLE
Setup an Engelsystem for helper's organization

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#25]
https://www.engelsystem.de/

**Comment by ri0t** [comment]
Ideally we have this and #24 on separate virtual machines (docker containers would be nice) so we can instantiate and back them up easily as well as deploy them anywhere. I would deploy them on a soon-to-be-gotten machine in the soundlab.

**Comment by ri0t** [comment]
Lookylooky: https://hub.docker.com/search/?q=engelsystem

**Comment by dvzrv** [comment]
Got a wiki to handle this: http://minilac.linuxaudio.org
