### ISSUE TITLE
Collect places where we can organize the conf

### ISSUE THREAD

**Issue by bgola** [linux-audio-berlin/LAC16#3]

**Comment by bgola** [comment]
Greenhouse - @brunogola will send an e-mail asking
Panke Culture http://www.pankeculture.com ~ 300 people on main room + gallery space + bar + open area - @brunogola will send an e-mail asking
C-Base ~200 people

**Comment by dvzrv** [comment]
If c-base goes smoothly, we need these spaces: http://eti-berlin.de/
We need a meeting with them, asap!

**Comment by dvzrv** [comment]
More information about how big the rooms are and what they offer, including photos can be found here: http://eti-berlin.de/proberaume/
