### ISSUE TITLE
Organize sub-conference at FROSCON

### ISSUE THREAD

**Issue by dvzrv** [linux-audio-berlin/LAC16#30]
There will be no academic side of LAC with miniLAC (too late for the review process to kick in until April, lack of resources, etc.), but the VOC (https://c3voc.de/) notified us about the possibility of doing a subconference at FROSCON (http://www.froscon.de/).
This could possibly host the academic side of things for LAC this year (yay, another sub-event!), but someone will have to get in touch with the froscon people and start planning this.
I won't personally have the time to do this. Any volunteers? :)

**Comment by derpeter** [comment]
Is this still planed? did you already got contact?

**Comment by dvzrv** [comment]
No contact. There's not much of a response from the community (yet).
We might be of help, but we will not be able to be main organizers.
