### ISSUE TITLE
Lable the cables

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#31]
Everything we need to use during the conference needs to be labeled

**Comment by abrolag** [comment]
So is there a cable label table?
Sorry, couldn't resit.
Ah, my coat. Thanks :)

**Comment by dvzrv** [comment]
http://www.kira-fansub.com/wp-content/uploads/2012/03/ba-dum-tss1.jpg
;-)

**Comment by dvzrv** [comment]
closing for being a duplicate of #32
