### ISSUE TITLE
Label hardware

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#32]
Label all the hardware needed for the conference

**Comment by dvzrv** [comment]
All TU hardware for the seminar room is labeled.
AFAIK same counts for the VOC hardware, right @derpeter?

Only all used c-base hardware needs to be labeled then!

**Comment by derpeter** [comment]
right. we have collored cabelties an all our stuff

**Comment by dvzrv** [comment]
We can get the label printer of c-lab to do this job. We'll figure this out Friday latest.

**Comment by derpeter** [comment]
il try to remember to bring one but its good to have also a backup plan

**Comment by Excds** [comment]
Dave brought stickers that people can write their name on. Good enough, closing...
