### ISSUE TITLE
Make sure, the cleaning for Linux Audio Night is cared for.

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#34]
Really important to order this AT LEAST two weeks prior the event

**Comment by dvzrv** [comment]
atm. we think the scheduling for cleaning would be best after Linux Sound Night (so Sunday morning, before 10:00).

**Comment by dvzrv** [comment]
Cleaning is scheduled for Sunday morning, finished until 09:30h.
