### ISSUE TITLE
Print name tags (collect from the wiki)

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#37]
http://minilac.linuxaudio.org/index.php/Special:ListUsers

We'll probably have to reopen this ticket again shortly before the conference (because last minute people ;)

**Comment by dvzrv** [comment]
Actually, everyone in **this** list (http://minilac.linuxaudio.org/index.php/Category:User) is used for it. The other one is now full of spam users that are blocked.
If people haven't properly setup their account, that's not our concern.

Only use username? Would be fine by me.

**Comment by dvzrv** [comment]
Got enough labels now! They can be used with a laser printer and are sticky.

**Comment by Excds** [comment]
@dvzrv Wasn't this assigned to me? I just went and bought labels for printing...

**Comment by dvzrv** [comment]
Yes, I just got them for free... and it's only a few. You'll do the right thing! :)

**Comment by Excds** [comment]
Alignment got a little bit weird when printing, but I'm going to close this anyway. We have tags...
