### ISSUE TITLE
Ping Albert

### ISSUE THREAD

**Issue by bgola** [linux-audio-berlin/LAC16#4]

**Comment by dvzrv** [comment]
riot and I are going to do this on Friday

**Comment by dvzrv** [comment]
riot and I did, collected some more useful information.
More tickets will follow.

On July 1, 2015 8:27:31 PM CEST, Bruno Gola notifications@github.com wrote:

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/linux-audio-berlin/LAC16/issues/4

## 

David Runge
Köpenicker Straße 163
10997 Berlin
http://sleepmap.de

**Comment by dvzrv** [comment]
I now have the financial info from last year. Gonna send it to @ri0t
