### ISSUE TITLE
LSN coordination and planning meeting

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#40]
Like, we need:
- [ ] a dj to bridge setup gaps
- [ ] bar management
- [ ] lineup

**Comment by sonejostudios** [comment]
Hey! Is there any Subscription Papers for the Linux Sound Night and the Workshops/Presentations?

**Comment by ri0t** [comment]
subscription papers? We will not do any proceedings and as such will probably not deal with scientific papers this time. There's a schedule with self-registration here: http://minilac.linuxaudio.org/index.php/LinuxSoundNight#Timetable (Also for the regular events: http://minilac.linuxaudio.org/index.php/Schedule )
Cheers!

**Comment by Excds** [comment]
@ri0t I have a DJ setup I can bring and I can do that.

**Comment by ri0t** [comment]
You do realize we have a pioneer djm?

**Comment by ri0t** [comment]
OMG. :D :+1:
