### ISSUE TITLE
Equipment specifications

### ISSUE THREAD

**Issue by abrolag** [linux-audio-berlin/LAC16#41]
Can someone list the spec of equipment available.
e.g.
Mainhall projector resolution
Audio system inputs in conference room

**Comment by autostatic** [comment]
Good one! Allow me to specify our needs a bit more:
- What inputs does the main hall projector have? VGA, HDMI (mini or standard), DVI, Displayport (mini or standard)? Does it do Airplay? Or Chromecast?
- What kinds of inputs and outputs are available in the conference room? RCA, 1/4″ jack, 1/8″ jack, XLR, balanced, unbalanced, etc.
- Same for the main hall wrt the Linux Sound Night
- What mixer is available in the main hall?

**Comment by dvzrv** [comment]
Concerning the mixers: There are >=4 channel mixers of different brand available.
We'll get you the specs next week most likely.

The projector in the mainhall can be got over VGA (for sure), but also HDMI is possible afaik.
For the correct list of things, please wait! :)
I've assigned @Excds to this, he might be able to fill these things out sooner than I can.

**Comment by dvzrv** [comment]
@autostatic: visually it seems literally _every adapter available_ will be provided by the VOC (CCC's VideoOperationCenter).

Audio specs will be added over the coming weekend.

**Comment by autostatic** [comment]
That's great to hear! Looking forward to hearing more about the audio specs.

**Comment by dvzrv** [comment]
Alrite, for the Seminar room I updated them (http://minilac.linuxaudio.org/index.php/Seminar_room)
I'll try and be at c-base tonight to get the specs of the rest of them and fill them in.

**Comment by abrolag** [comment]
This might seem obvious, but what is a 'beamer'? It's not a term I've heard in the UK :(

**Comment by dvzrv** [comment]
@abrolag: You're right. I've fixed that (for the seminar room).
Will have more info on the projector/beamer for the mainhall after Tuesday night, when we've discussed things like screengrabbing with the VOC.

**Comment by abrolag** [comment]
That's a seriously good spec! I should be able to plug straight into my laptop without any problem!

For my workshop I asked for a dumb midi/usb keyboard. Is there any chance of one being available? I can work without it if necessary, but it'd be much better with one :)

**Comment by abrolag** [comment]
Any news on availability of a MIDI keyboard on the conference room?
Sorry if this is the wrong place. I don't know where else to ask.

**Comment by falkTX** [comment]
I have a small one that I can bring.

**Comment by dvzrv** [comment]
@abrolag there are some in the soundlab, too. I can get you the specs later tonight, latest tomorrow night and will update the wiki accordingly.

**Comment by Excds** [comment]
@abrolag I have a CME U5 in the soundlab that can be used. I was also thinking to bring some other controllers that people can borrow. So I can provide a Novation Launchpad, Akai LPK25 and LPD8.

If need be I could also bring a CME UF70 and an FCB1010.

**Comment by abrolag** [comment]
Thanks everyone. It seems we are suddenly overwhelmed with choice! If there are some already there I'm sure that will be fine.

**Comment by Excds** [comment]
@abrolag I'm thinking about skipping the FCB1010 (foot controller) and the UF70 (76 keys keyboard) since they're a bit large and not so portable. Are the other ones suggested enough?

**Comment by abrolag** [comment]
Just a dumb keyboard (say 49 keys) would be fine for me. I'll only be doing one-handed stuff. Trying to use a virtual keyboard tends to detract from the impact ;)

**Comment by Excds** [comment]
@abrolag The small (but very portable) LPK25 is only 25. But I have a larger 49 key keyboard at c-base. We'll figure it out. We've got stuff. :-)

**Comment by abrolag** [comment]
Thanks - even the 25 would be better than a virtual one ;)
I'll be 'off-grid' later today. I'm travelling to Berlin by train from England first thing tomorrow (making a holiday of it).
See you all soon :)

**Comment by Excds** [comment]
@abrolag Have a nice trip! :-)
