### ISSUE TITLE
Get coffee supplies working

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#42]
We'll need cups, machines and coffee. Cultorga probably has cups & machines, riot could get FAIR and very good coffee from fairbindung. (A little bit more expensive though!)

**Comment by Excds** [comment]
@ri0t cven said we should email (forgot the name) from Culturorga about the coffee machines.

**Comment by RhizomaticNomad** [comment]
Alternativ könnte ich Kaffee bei Aroma Zapatista https://www.aroma-zapatista.de/catalog/category/view/id/11 bestellen ... ist etwas günstiger und die Gewinne gehen direkt an eine emanzipatorische, solidarische Bewegung.

**Comment by dvzrv** [comment]
@RhizomaticNomad guess you just volunteered? :)

**Comment by RhizomaticNomad** [comment]
yes I did.
how will we manage the money and how much should I order; do you prefer one kind/flavour or different?

**Comment by dvzrv** [comment]
@RhizomaticNomad: okay, that's great! I'm not much of a coffee drinker anymore, so... you decide!
Same counts for the money collection. Let us know, what it'll cost and we'll try to cover this by donations.
Currently there's no other way. If you can think of any, let us know.
Also: If you'd like to boost the donations and take care of them during the event, please go for it.
Will open another issue for it.

**Comment by abrolag** [comment]
How about having a clearly marked donation pot in some central location. I'd be more than happy to drop a few Euro in from time to time - especially if there was an active display somewhere showing what needs to be covered.

**Comment by dvzrv** [comment]
@RhizomaticNomad: what's the status on this?
http://minilac.linuxaudio.org/index.php/Category:User <- these are all users that currently have setup their user page properly and are (most likely) coming

**Comment by RhizomaticNomad** [comment]
Depends on how much is needed, I've 10 packages espresso à 250g right now, I can't imganie how much is possibly needed. And if "normal" coffee instead of espresso is needed, too?

**Comment by Excds** [comment]
@RhizomaticNomad The coffee machines we will have only use normal coffee. We don't have an espresso machine. :-(

**Comment by RhizomaticNomad** [comment]
OK, and what do you think how much we'll probably need, can also get the filter coffee.

**Comment by Excds** [comment]
I think we'd need at least 5kg of coffee. We can judge the coffee consumption on Saturday and in worst case we can go get more.

**Comment by RhizomaticNomad** [comment]
I have 5kg of coffee right now and can get more if we need ... or give unused packages back if it's more than we need.
The price is 8€/500g, to donate this I can't afford unfortunately.

**Comment by Excds** [comment]
@RhizomaticNomad Ok, we'll solve the expenses. Closing this ticket now since we have the coffee.

**Comment by Excds** [comment]
Ah, right, we need milk and sugar as well. Reopening...

**Comment by RhizomaticNomad** [comment]
I'll bring 3l milk, 2l rice soy drink and a package of sugar, but I won't arrive before half past 10, maybe 11. So it would be good if somebody else also picks up a bit.

**Comment by ri0t** [comment]
Weee - good coffee! Do we have enough supplies? If not, reopen ticket.
