### ISSUE TITLE
Generate template for infobeamer

### ISSUE THREAD

**Issue by dvzrv** [linux-audio-berlin/LAC16#43]
We need to generate a template (css) with pictures (from matelight) for the infobeamer.
This weekend!

**Comment by ri0t** [comment]
Looky, looky: https://github.com/linux-audio-berlin/info-beamer-minilac16

Still have to replace the chaotic letter changes - those are tooo 29c3'y.
Also, is this all we need for the VOC?

**Comment by ri0t** [comment]
Yah, works, apparently \o/
