### ISSUE TITLE
Getting CCC hardware

### ISSUE THREAD

**Issue by dvzrv** [linux-audio-berlin/LAC16#44]
CCC hardware will be grabbed with VOC team members on the 7th

**Comment by dvzrv** [comment]
I wrote to bengoshi to get the status of the insurance on external hardware.

**Comment by dvzrv** [comment]
Insurance is on the way. A tad more expensive, than I thought, but still within limits, I think.

**Comment by ri0t** [comment]
Superb! I'd say this - and attached - was one of major milestones! Oh, hello, cap'n obvious!
