### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by dvzrv** [linux-audio-berlin/LAC16#48]
There are some open positions that we need to cover with donations or cover ourselves.
Namely those are:
- [x] Coffee (#42) (62€)
- [x] Transportation of equipment (#45 #44 ) (39€ + delivery (20160413) for mate, thx ryo!)
- [x] Extra cleaning (#34) (100€)
- [x] Insurance for VOC equipment (#44) (190,4€)
- [x] postage of mainhall frame grabber for test (~20€)

**Comment by ri0t** [comment]
This needs dire mention in #51

**Comment by dvzrv** [comment]
@RhizomaticNomad any update on the price for coffee, or are you donating? :)

**Comment by dvzrv** [comment]
Added this to the opening lecture.

**Comment by dvzrv** [comment]
Added a donation page: http://minilac.linuxaudio.org/index.php/Donation

**Comment by RhizomaticNomad** [comment]
Till now coffee is 82 Euro, tomorrow I'll add the other expenses.

**Comment by dvzrv** [comment]
@RhizomaticNomad we still have 3 packs left!
You can come and grab them. I think @ri0t stored them in the soundlab

**Comment by dvzrv** [comment]
We generated 330€ in donations so far.
Seems we can cover insurance and cleaning from that.
The rest will have to be split amongst us.
Transportation is still in limbo, but will not be 60€ I think.

**Comment by bgola** [comment]
@dvzrv count on me to split as well

**Comment by dvzrv** [comment]
@brunogola Thanks! Will get back to you, once this has settled!

**Comment by Excds** [comment]
@dvzrv Me too.

Oh, and I owe you for lunch as well.

**Comment by dvzrv** [comment]
@Excds hehe, that's correct! (and I was counting you in already! :P)

**Comment by ri0t** [comment]
What do you mean with "Split amongst us"?

```
>>> 64+60+100+190
414
>>> 414-330
84
>>> 84/5.0  # Participants here ;)
16.8
```

**Comment by ri0t** [comment]
Oh, I forogt, a few packages of coffee are still left - either to generate happiness in form of further donations or getting them back and reducing costs. (Excellent Coffee - thanks again, @RhizomaticNomad for getting the good stuff)

**Comment by bgola** [comment]
i might be interested in buying one of those packages to reduce costs, if you want to ;) 
I just finished my last coffee package at home, im desperate.

**Comment by RhizomaticNomad** [comment]
I can pick up the coffee on Wednesday evening and give the three packages back, so that the costs get reduced of 24€ and are in total 58€ then. For milk and sugar I also spent 4,40€, so coffee can get calculated with 62€.
@ri0t are you @C-Base Wednesday around 8pm?
Splitting the rest of the costs is OK for me, too.

**Comment by dvzrv** [comment]
@ri0t these are not the complete costs yet. we'll know all after tomorrow evening.

**Comment by RhizomaticNomad** [comment]
@brunogola if you like to just grab one of the coffee, I'll take what's left there.

**Comment by dvzrv** [comment]
Donations now at 340€ (thanks!).

**Comment by dvzrv** [comment]
@derpeter spend ~20€ on the shipment for the frame grabber in the mainhall, so we (c-base) could try it out.
I'll ask for that money at the circle on Thursday, as we'll now indeed get the exact same device for c-base (test was successful, so to speak ;-) ).

**Comment by dvzrv** [comment]
Just paid @RhizomaticNomad earlier this evening (and have a bill for it).
Brought all TU stuff back to the studio for mate (thx ryo@c-base!) and paid myself the one way transportation (against receipt).

**Comment by dvzrv** [comment]
c-base took care of the rest of our expenses and will pay @derpeter for the shipment of the frame grabber.
Will pay the insurance by bank transfer later.
SPACE STATIONS RULE!
