### ISSUE TITLE
Setting up hardware for streaming

### ISSUE THREAD

**Issue by dvzrv** [linux-audio-berlin/LAC16#52]
The streaming hardware will be setup by cven and @derpeter on Friday, 20160408 for mainhall.
The streaming and audio hardware for the seminar room will be setup by @dvzrv and @derpeter on Thursday, 20160407 and Friday, 20160408.

**Comment by derpeter** [comment]
OK current plan is:
we grab everthing we need from CCCB on 6.4 and bring it either to the owncloud office or right to the cbase.

We need to fetch one machine from the ccc warehouse which we can do when ever its suitable for the logistig. Getting the stuff from cccb can be done by drive now.

Framegrabber for the mainhall is reuqested, i assume we get an answer this week.

**Comment by ri0t** [comment]
Totally works! Awesome! Huge thumbs up to @derpeter, the whole c3voc and everyone else involved.
