### ISSUE TITLE
Infobeamer machinery on board

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#54]
Mainhall: Chromebox from King Rubbel is probably going to run infobeamer
Seminarroom: Needs a box
Weltenbaulab: Needs installation on c-lib box (riot)
Soundlab: Needs fixing of OpenGL3 problem (possibly install the RPi variant)
HE1: See Mainhall - or should we have a dedicated display up there?

**Comment by dvzrv** [comment]
according to @derpeter, the VOC will provide a bunch of preinstalled RPi{1,2,3}s with info-beamer.
I think we can close this.

**Comment by ri0t** [comment]
Yes, then we can - we could still try to provide another one on the c-lib - i just don't have admin access there (It is an Arch)

**Comment by derpeter** [comment]
We want to use "hosted infobeamer" therefore it needs to be raspi hardware. 
I will pick some pis up later today
