### ISSUE TITLE
Press announcement needs to go out TODAY.

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#56]
We need this translated to -press- english (for slashdot etc):

Vom 8.-10. April 2016 findet in der Raumstation c-base unter Berlin Mitte die diesjährige Linux Audio Conference in etwas kleinerem Rahmen -  als miniLAC - statt, da die Teilnehmerzahl auf 150 Audio Hacker begrenzt ist.
Zahlreiche Entwickler und Anwender der vielfältigen Linux Audio Szene kommen hier zusammen. Es wird 3 Tage lang über aktuelle Entwicklungen vorgetragen und diskutiert sowie gemeinsamer Wissensaustausch in Workshops und Hack-Events betrieben. 
Für weitere Informationen und die (notwendige) Registrierung zum Besuch des Events, besuchen sie http://minilac.linuxaudio.org.

There is an etherpad here: https://pad.sleepmap.de/p/minilac-pressannouncement

**Comment by dvzrv** [comment]
updated, should be good to go.

**Comment by ri0t** [comment]
- Golem - erledigt
- Heise - erledigt
- Linux Weekly News - erledigt
- Linux Magazin - erledigt
- CreateDigitalMusic - erledigt
- Hack a Day - erledigt

**Comment by ri0t** [comment]
- [x] Linux Magazin: http://www.linux-magazin.de/NEWS/Linux-Audio-Konferenz-in-Berlin
- [ ] Golem
- [ ] Heise
- [x] LWN http://lwn.net/Calendar/
- [ ] CDM
- [ ] HaD
