### ISSUE TITLE
Space X Launch on Friday ~22:45

### ISSUE THREAD

**Issue by ri0t** [linux-audio-berlin/LAC16#57]
Bergie already mentioned, that there will probably (90%) be a spacex launch on friday night.
I'd LOVE to have this supported by ambient music from the participants! That would be a nice challenge.
The launch audio (just  a few minutes - countdown etc) would have to be mixed in, no other "noise" (cheering etc)..
More details + countdown at:
https://spacexstats.com/missions/spacex-crs-8

**Comment by bergie** [comment]
I think the best livestream for this would be the SpaceX "Technical livestream", since that only has the launchnet radio communications (including countdown) and some rocket noises. No narration or cheering.

Here's an example how that might sound: https://youtu.be/sIkPP2LM8DU?t=8m26s

**Comment by ri0t** [comment]
It will be done.

**Comment by ri0t** [comment]
Needs to be entered into the schedule :)

**Comment by dvzrv** [comment]
@bergie please register with the wiki and do it! :)

**Comment by bergie** [comment]
@dvzrv which wiki?

**Comment by dvzrv** [comment]
http://minilac.linuxaudio.org

**Comment by ri0t** [comment]
Aah, the schedule is locked. I will add it later.

**Comment by ri0t** [comment]
Doesn't even need to go to the schedule - is  in the wiki now :)
