### ISSUE TITLE
Check recording/streaming equipment and possibilites

### ISSUE THREAD

**Issue by bgola** [linux-audio-berlin/LAC16#7]
- location
- internet connection
- equipment for video recording

we should ask riot about c-base equipment, knowledge and people to do that

**Comment by bgola** [comment]
we should check with film/audio students that need pratical work if we can use their help for this task

**Comment by dvzrv** [comment]
We should also contact the CCC about it. They would bring everything we need, no/little self-involvement needed, if they're up for it and have the time!

**Comment by dvzrv** [comment]
Will write to http://c3voc.de next week, when we know date specifics.
We should mention gstreamer and possibly invite them to give a talk about it... it's their baby (concerning audio/video streaming nstuff).

**Comment by dvzrv** [comment]
I wrote to the VOC, we'll see what they have to say.
