### ISSUE TITLE
Find spaces for the concerts

### ISSUE THREAD

**Issue by bgola** [linux-audio-berlin/LAC16#8]

**Comment by dvzrv** [comment]
Electro-acoustic/experimental:
NK - http://www.nkprojekt.de/
Ausland - http://ausland-berlin.de/
Ohm - http://www.ohmberlin.com/
Urban Spree - http://urbanspree.com/

**Comment by dvzrv** [comment]
NK is out of business from September on.
Other close locations (on the other side of the Spree, a little further up) are:
Radialsystem V - http://www.radialsystem.de/rebrush/downloads/Praesentation_RADIALSYSTEM%20V_web.pdf
Marie Antoinette - http://www.marie-antoinette-berlin.de/
Both are bookable places, but possibly out of range. We'll see.

**Comment by RhizomaticNomad** [comment]
both next to Ostkreuz:
about:blank http://aboutparty.net ... indirectly I know some people of that collective
Zukunft http://zukunft-ostkreuz.de

**Comment by dvzrv** [comment]
All further collections and updates on it should be done in the etherpad:
http://linuxaudio.berlin:9001/p/sponsoring-locations

**Comment by dvzrv** [comment]
If external concerts are still a thing, we need to find out where/when asap, else close this.

**Comment by dvzrv** [comment]
Awaiting reply from Spektrum (http://spektrumberlin.de) and Ohm for possible sound night on April 9th.

**Comment by dvzrv** [comment]
Spektrum is saying no to Saturday 9th April.
I submitted another request for the Sunday (10th April).

**Comment by ri0t** [comment]
More Meh. Should indeed something pop up, open another issue..
