### ISSUE TITLE
List and get replies of possible sponsors

### ISSUE THREAD

**Issue by bgola** [linux-audio-berlin/LAC16#9]

**Comment by ri0t** [comment]
Linux related
- [ ] Bitwig  (obviously, riot is on it)
- [ ] Soundcloud
- [ ] u-He
- [ ] Nagualsounds(?): http://www.nagualsounds.de/
- [ ] c't (heise) (http://www.heise.de/ct/) (dave through Joachim Heintz)

Not-so-Linux related
- [ ] Justmusic
- [ ] De-Bug: http://de-bug.de/
- [ ] StageTec: http://www.stagetec.com/de/
- [ ] MFBerlin: http://mfberlin.de/en/home/
- [ ] Native Instruments
- [ ] Ableton
- [ ] Eve Audio
- [ ] Tegeler Audio Manufaktur: https://www.tegeler-audio-manufaktur.de/
- [ ] Neumann: http://www.neumann.com/?id=2&lang=en (dave through TU Neumann contact)
- [ ] Kirsch Audio: http://www.kirsch-audio.com/

**Comment by dvzrv** [comment]
Dumped sponsoring
